spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: 'Planet Eris Application'
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always
server:
  http2:
    enabled: true
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-alias: domain
